apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ticketing-app
build:
  googleCloudBuild:
    projectId: ticketing-app-372411
  artifacts:
  - image: gcr.io/ticketing-app-372411/auth
    context: auth
    sync: 
      manual:
        - dest: .
          src: 'src/**/*.ts'
    docker:
      dockerfile: Dockerfile
  - image: mer5432100/client
    context: client
    sync: 
      manual:
        - dest: .
          src: 'src/**/*.js'
    docker:
      dockerfile: Dockerfile
  - image: mer5432100/orders
    context: orders
    sync: 
      manual:
        - dest: .
          src: 'src/**/*.ts'
    docker:
      dockerfile: Dockerfile
  - image: mer5432100/tickets
    context: tickets
    sync: 
      manual:
        - dest: .
          src: 'src/**/*.ts'
    docker:
      dockerfile: Dockerfile
  - image: mer5432100/expiration
    context: expiration
    sync: 
      manual:
        - dest: .
          src: 'src/**/*.ts'
    docker:
      dockerfile: Dockerfile
  - image: mer5432100/payments
    context: payments
    sync: 
      manual:
        - dest: .
          src: 'src/**/*.ts'
    docker:
      dockerfile: Dockerfile
  
  
 
manifests:
  rawYaml:
  - infra/k8s/auth-depl.yaml
  - infra/k8s/auth-mongo-depl.yaml
  - infra/k8s/client-depl.yaml
  - infra/k8s/ingress-srv.yaml
  - infra/k8s/nats-depl.yaml
  - infra/k8s/orders-depl.yaml
  - infra/k8s/orders-mongo-depl.yaml
  - infra/k8s/tickets-depl.yaml
  - infra/k8s/tickets-mongo-depl.yaml
  - infra/k8s/expiration-redis-depl.yaml
  - infra/k8s/expiration-depl.yaml
  - infra/k8s/payments-depl.yaml
  - infra/k8s/payments-mongo-depl.yaml
  - infra/k8s-dev/*
