apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ticketing-app
build:
  local:
      push: false
  
  
    
  artifacts:
  - image: mert5432100/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
       manual:
        - dest: .
          src: src/**/*.ts
  - image: mert5432100/client
    context: client
    docker:
          dockerfile: Dockerfile
    sync:
       manual:
        - dest: .
          src: '**/*.js'
  - image: mert5432100/tickets
    context: tickets
    docker:
      dockerfile: Dockerfile
    sync:
       manual:
        - dest: .
          src: src/**/*.ts
  - image: mert5432100/orders
    context: orders
    docker:
      dockerfile: Dockerfile
    sync: 
      manual:
        - dest: .
          src: src/**/*.ts
manifests:
  rawYaml:
  - infra/k8s/*
